"""Export selected Casino concept props and their Unity rebuild code into the kit.

Run from the repository root. Existing prefab GUIDs are preserved.
"""
from pathlib import Path
import math
import re
import uuid

ROOT = Path(__file__).resolve().parents[1]
KIT = ROOT / 'Assets/Content/StyleKit'
scene = (ROOT / 'Assets/Scenes/Casino_Test/Casino.unity').read_text()
blocks = re.findall(r'^--- !u!\d+ &-?\d+\n.*?(?=^--- !u!|\Z)', scene, re.M | re.S)
by_id = {re.search(r'&(-?\d+)', b)[1]: b for b in blocks}
transforms = {i: b for i, b in by_id.items() if b.startswith('--- !u!4 ')}

def vec(block, field):
    return tuple(float(x) for x in re.search(field + r': {x: ([^,]+), y: ([^,]+), z: ([^}]+)}', block).groups())

def fmt(v):
    return ', '.join(f'{n:.8g}f' if '.' in f'{n:.8g}' else f'{n:.8g}f' for n in v)

def yamlvec(v):
    return '{' + ', '.join(f'{a}: {b:.8g}' for a, b in zip('xyz', v)) + '}'

def name(t):
    go = re.search(r'm_GameObject: {fileID: (\d+)}', t)[1]
    return re.search(r'm_Name: (.*)', by_id[go])[1].removeprefix('Casino_')

mat_guids = {}
for meta in (KIT / 'Materials').glob('*.mat.meta'):
    mat_guids[re.search(r'guid: (\w+)', meta.read_text())[1]] = meta.name[2:-9]
fields = {'CarpetRed':'carpetRed', 'FeltGreen':'feltGreen', 'WoodDark':'woodDark',
          'BrassGold':'brassGold', 'PlasterCream':'plasterCream', 'FabricBurgundy':'fabricBurgundy',
          'ChipBlack':'chipBlack', 'ScreenGlow':'screenGlow', 'ChipWhite':'chipWhite', 'ChipRed':'chipRed', 'FeltGreen':'feltGreen'}
specs = [
    ('casinoTableSet', 'Kit_CasinoTableSet', (-3.6, 0, -1), lambda n,p: (n in ('Kit_Table_Round','Kit_Chair','ChipStack','PlayingCard') and abs(p[0]+3.6)<1.5 and abs(p[2]+1)<1.5)),
    ('slotMachine', 'Kit_SlotMachine', (-7.5,0,-4.5), lambda n,p: n.startswith('Slot') and abs(p[0]+7.5)<.6 and abs(p[2]+4.5)<.5),
    ('barCounter', 'Kit_BarCounter', (-5.8,0,9), lambda n,p: n in ('BarBase','BarTop','BarGoldFace')),
    ('barStool', 'Kit_BarStool', (-7.3,0,7.9), lambda n,p: n.startswith('BarStool') and abs(p[0]+7.3)<.01),
    ('cashierCounter', 'Kit_CashierCounter', (6.7,0,10), lambda n,p: n in ('CashierCounter','CashierTop','CashierBrassBars','CashierHeader')),
    ('chandelier', 'Kit_Chandelier', (0,3.48,-2), lambda n,p: n.startswith('Chandelier') and abs(p[2]+2)<1),
    ('casinoWallPanel', 'Kit_CasinoWallPanel', (0,0,0), lambda n,p: False),
]
code = ['// Casino visual props. Generated by tools/export_casino_stylekit.py.\nusing HighStakes.Environment;\nusing UnityEditor;\nusing UnityEngine;\n\npublic static class CasinoStyleKitBuilder\n{\n',
'''    [MenuItem("High Stakes/Build Casino Furnishings")]
    public static void BuildCasinoFurnishings()
    {
        var kit = AssetDatabase.LoadAssetAtPath<SharedStyleKit>("Assets/Content/StyleKit/SharedStyleKit.asset");
        if (kit == null) { Debug.LogError("Build the shared style kit first."); return; }
        Build(kit);
        EditorUtility.SetDirty(kit);
        AssetDatabase.SaveAssets();
    }

    public static void Build(SharedStyleKit kit)
    {
''']
asset_path = KIT / 'SharedStyleKit.asset'
asset = asset_path.read_text()
for index,(field,prefab,anchor,select) in enumerate(specs):
    selected = [i for i,t in transforms.items() if 'm_Father: {fileID: 0}' in t and select(name(t),vec(t,'m_LocalPosition'))]
    # A modular 2m x 3m panel, rather than the concept's 22m wall.
    if field == 'casinoWallPanel':
        selected = [i for i,t in transforms.items() if name(t) in ('SideWall','Wainscot','GoldChairRail','CrownMolding')][:4]
    assert selected, prefab
    root_go, root_t = 900000000 + index*10, 900000001 + index*10
    go_template = by_id[re.search(r'm_GameObject: {fileID: (\d+)}', transforms[selected[0]])[1]]
    root = re.sub(r'&\d+',f'&{root_go}',go_template, count=1)
    root = re.sub(r'm_Component:\n(?:  - component:.*\n)+', f'm_Component:\n  - component: {{fileID: {root_t}}}\n',root)
    root = re.sub(r'm_Name: .*','m_Name: '+prefab,root)
    transform = transforms[selected[0]]
    transform = re.sub(r'&\d+',f'&{root_t}',transform,count=1)
    transform = re.sub(r'm_GameObject: .*',f'm_GameObject: {{fileID: {root_go}}}',transform)
    transform = re.sub(r'm_LocalPosition: .*','m_LocalPosition: {x: 0, y: 0, z: 0}',transform)
    transform = re.sub(r'm_LocalRotation: .*','m_LocalRotation: {x: 0, y: 0, z: 0, w: 1}',transform)
    transform = re.sub(r'm_LocalScale: .*','m_LocalScale: {x: 1, y: 1, z: 1}',transform)
    transform = re.sub(r'm_Children:\n(?:  - .*\n)*|m_Children: \[\]\n','m_Children:\n'+''.join(f'  - {{fileID: {i}}}\n' for i in selected),transform)
    output = ['%YAML 1.1\n%TAG !u! tag:unity3d.com,2011:\n',root,transform]
    code.append(f'        var {field} = new GameObject("{prefab}");\n')
    for i in selected:
        t=transforms[i]; n=name(t); pos=tuple(a-b for a,b in zip(vec(t,'m_LocalPosition'),anchor)); scale=vec(t,'m_LocalScale')
        if field=='casinoWallPanel':
            layout={'SideWall':((0,1.5,0),(2,3,.15)), 'Wainscot':((0,.65,-.1),(2,1.3,.08)), 'GoldChairRail':((0,1.32,-.16),(2,.06,.04)), 'CrownMolding':((0,2.85,-.16),(2,.15,.08))}
            pos,scale=layout[n]
        if n == 'ChipStack':
            # Four 39mm chips; cylinder Y scale is half its visible height.
            pos = (pos[0], .762, pos[2])
            scale = (.039, .0066, .039)
        if n == 'BarStoolStem':
            scale = (.12, .35, .12)
        if n == 'ChandelierStem':
            scale = (.065, .3, .065)
        edited = re.sub(r'm_LocalPosition: .*','m_LocalPosition: '+yamlvec(pos),t)
        edited = re.sub(r'm_LocalScale: .*','m_LocalScale: '+yamlvec(scale),edited)
        edited = edited.replace('m_Father: {fileID: 0}', f'm_Father: {{fileID: {root_t}}}')
        todo=[i]; included=set()
        while todo:
            tid=todo.pop(); tb=transforms[tid]; gid=re.search(r'm_GameObject: {fileID: (\d+)}',tb)[1]
            included.add(gid)
            included.update(re.findall(r'component: {fileID: (\d+)}',by_id[gid]))
            todo.extend(re.findall(r'^  - {fileID: (\d+)}',tb,re.M))
        output.extend(edited if ident==i else by_id[ident] for ident in by_id if ident in included)
        rotation = re.search(r'm_LocalRotation: {x: ([^,]+), y: ([^,]+), z: ([^,]+), w: ([^}]+)}',t).groups()
        rot = fmt(tuple(float(v) for v in rotation))
        if n in ('Kit_Table_Round','Kit_Chair'):
            ref='tableRound' if n=='Kit_Table_Round' else 'chair'
            code.append(f'        Place(kit.{ref}, {field}, new Vector3({fmt(pos)}), new Quaternion({rot}));\n')
        else:
            go=by_id[re.search(r'm_GameObject: {fileID: (\d+)}',t)[1]]
            components=[by_id[c] for c in re.findall(r'component: {fileID: (\d+)}',go)]
            renderer=next(c for c in components if 'MeshRenderer:' in c)
            mesh=next(c for c in components if 'MeshFilter:' in c)
            material=fields[mat_guids[re.search(r'guid: (\w+)',renderer)[1]]]
            primitive={10202:'Cube',10206:'Cylinder',10207:'Sphere'}[int(re.search(r'm_Mesh: {fileID: (\d+)',mesh)[1])]
            code.append(f'        Piece({field}, "{n}", PrimitiveType.{primitive}, new Vector3({fmt(pos)}), new Vector3({fmt(scale)}), new Quaternion({rot}), kit.{material});\n')
    code.append(f'        kit.{field} = Save({field});\n\n')
    path=KIT / 'Prefabs' / (prefab+'.prefab')
    path.write_text(''.join(output),encoding='utf-8',newline='\n')
    meta=Path(str(path)+'.meta')
    guid=re.search(r'guid: (\w+)',meta.read_text())[1] if meta.exists() else uuid.uuid4().hex
    meta.write_text(f'fileFormatVersion: 2\nguid: {guid}\nPrefabImporter:\n  externalObjects: {{}}\n  userData:\n  assetBundleName:\n  assetBundleVariant:\n')
    entry=f'  {field}: {{fileID: {root_go}, guid: {guid}, type: 3}}\n'
    asset=re.sub(r'^  '+field+r':.*\n', '',asset, flags=re.M)+entry
    print(prefab, len(selected), 'parts')
asset_path.write_text(asset,encoding='utf-8',newline='\n')
code.append('''    }

    static void Place(GameObject prefab, GameObject parent, Vector3 position, Quaternion rotation)
    {
        var go = (GameObject)PrefabUtility.InstantiatePrefab(prefab, parent.transform);
        go.transform.localPosition = position;
        go.transform.localRotation = rotation;
    }

    static void Piece(GameObject parent, string name, PrimitiveType type, Vector3 position, Vector3 scale, Quaternion rotation, Material material)
    {
        var go = GameObject.CreatePrimitive(type);
        go.name = name;
        go.transform.SetParent(parent.transform, false);
        go.transform.localPosition = position;
        go.transform.localScale = scale;
        go.transform.localRotation = rotation;
        go.GetComponent<Renderer>().sharedMaterial = material;
        go.GetComponent<Renderer>().shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
        Object.DestroyImmediate(go.GetComponent<Collider>());
        if (type == PrimitiveType.Cube) go.AddComponent<BoxCollider>();
        else if (type == PrimitiveType.Sphere) go.AddComponent<SphereCollider>();
        else go.AddComponent<MeshCollider>().convex = true;
    }

    static GameObject Save(GameObject root)
    {
        foreach (var transform in root.GetComponentsInChildren<Transform>()) transform.gameObject.isStatic = true;
        var prefab = PrefabUtility.SaveAsPrefabAsset(root, "Assets/Content/StyleKit/Prefabs/" + root.name + ".prefab");
        Object.DestroyImmediate(root);
        return prefab;
    }
}
''')
cs=ROOT / 'Assets/Scripts/Environment/Editor/CasinoStyleKitBuilder.cs'
cs.write_text(''.join(code),encoding='utf-8',newline='\n')
meta=Path(str(cs)+'.meta')
if not meta.exists():
    meta.write_text(f'fileFormatVersion: 2\nguid: {uuid.uuid4().hex}\nMonoImporter:\n  externalObjects: {{}}\n  serializedVersion: 2\n  defaultReferences: []\n  executionOrder: 0\n  icon: {{instanceID: 0}}\n  userData:\n  assetBundleName:\n  assetBundleVariant:\n')
