// Casino visual props. Generated by tools/export_casino_stylekit.py.
using HighStakes.Environment;
using UnityEditor;
using UnityEngine;

public static class CasinoStyleKitBuilder
{
    [MenuItem("High Stakes/Build Casino Furnishings")]
    public static void BuildCasinoFurnishings()
    {
        var kit = AssetDatabase.LoadAssetAtPath<SharedStyleKit>("Assets/Content/StyleKit/SharedStyleKit.asset");
        if (kit == null) { Debug.LogError("Build the shared style kit first."); return; }
        Build(kit);
        EditorUtility.SetDirty(kit);
        AssetDatabase.SaveAssets();
    }

    public static void Build(SharedStyleKit kit)
    {
        var casinoTableSet = new GameObject("Kit_CasinoTableSet");
        Place(kit.tableRound, casinoTableSet, new Vector3(0f, 0f, 0f), new Quaternion(0f, 0f, 0f, 1f));
        Place(kit.chair, casinoTableSet, new Vector3(0.9545942f, 0f, 0.95459415f), new Quaternion(0f, 0.92387953f, 0f, -0.38268343f));
        Place(kit.chair, casinoTableSet, new Vector3(0.3494057f, 0f, -1.3039999f), new Quaternion(0f, 0.13052619f, 0f, -0.99144486f));
        Place(kit.chair, casinoTableSet, new Vector3(-1.3039999f, 0f, 0.34940571f), new Quaternion(0f, -0.79335334f, 0f, -0.60876143f));
        Piece(casinoTableSet, "ChipStack", PrimitiveType.Cylinder, new Vector3(-0.3f, 0.762f, 0f), new Vector3(0.039f, 0.0066f, 0.039f), new Quaternion(0f, 0f, 0f, 1f), kit.chipRed);
        Piece(casinoTableSet, "ChipStack", PrimitiveType.Cylinder, new Vector3(0.3f, 0.762f, 0f), new Vector3(0.039f, 0.0066f, 0.039f), new Quaternion(0f, 0f, 0f, 1f), kit.chipWhite);
        Piece(casinoTableSet, "PlayingCard", PrimitiveType.Cube, new Vector3(0f, 0.761f, 0.25f), new Vector3(0.09f, 0.005f, 0.13f), new Quaternion(0f, 0.13052619f, 0f, 0.99144486f), kit.chipWhite);
        kit.casinoTableSet = Save(casinoTableSet);

        var slotMachine = new GameObject("Kit_SlotMachine");
        Piece(slotMachine, "SlotCabinet", PrimitiveType.Cube, new Vector3(0f, 0.95f, 0f), new Vector3(0.72f, 1.9f, 0.7f), new Quaternion(0f, 0f, 0f, 1f), kit.chipBlack);
        Piece(slotMachine, "SlotGoldBezel", PrimitiveType.Cube, new Vector3(0.375f, 1.36f, 0f), new Vector3(0.05f, 0.86f, 0.62f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        Piece(slotMachine, "SlotScreen", PrimitiveType.Cube, new Vector3(0.407f, 1.36f, 0f), new Vector3(0.025f, 0.71f, 0.49f), new Quaternion(0f, 0f, 0f, 1f), kit.screenGlow);
        Piece(slotMachine, "SlotReel", PrimitiveType.Cube, new Vector3(0.425f, 1.35f, -0.15f), new Vector3(0.015f, 0.22f, 0.1f), new Quaternion(0f, 0f, 0f, 1f), kit.chipWhite);
        Piece(slotMachine, "SlotReel", PrimitiveType.Cube, new Vector3(0.425f, 1.35f, 0f), new Vector3(0.015f, 0.22f, 0.1f), new Quaternion(0f, 0f, 0f, 1f), kit.chipRed);
        Piece(slotMachine, "SlotReel", PrimitiveType.Cube, new Vector3(0.425f, 1.35f, 0.15f), new Vector3(0.015f, 0.22f, 0.1f), new Quaternion(0f, 0f, 0f, 1f), kit.chipWhite);
        Piece(slotMachine, "SlotConsole", PrimitiveType.Cube, new Vector3(0.45f, 0.87f, 0f), new Vector3(0.28f, 0.09f, 0.68f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        Piece(slotMachine, "SlotMarquee", PrimitiveType.Cube, new Vector3(0f, 2.04f, 0f), new Vector3(0.8f, 0.2f, 0.76f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        kit.slotMachine = Save(slotMachine);

        var barCounter = new GameObject("Kit_BarCounter");
        Piece(barCounter, "BarBase", PrimitiveType.Cube, new Vector3(0f, 0.5f, 0f), new Vector3(4.5f, 1f, 0.85f), new Quaternion(0f, 0f, 0f, 1f), kit.woodDark);
        Piece(barCounter, "BarTop", PrimitiveType.Cube, new Vector3(0f, 1.04f, 0f), new Vector3(4.8f, 0.12f, 1.05f), new Quaternion(0f, 0f, 0f, 1f), kit.chipBlack);
        Piece(barCounter, "BarGoldFace", PrimitiveType.Cube, new Vector3(0f, 0.72f, -0.45f), new Vector3(4.4f, 0.06f, 0.04f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        kit.barCounter = Save(barCounter);

        var barStool = new GameObject("Kit_BarStool");
        Piece(barStool, "BarStoolStem", PrimitiveType.Cylinder, new Vector3(0f, 0.35f, 0f), new Vector3(0.12f, 0.35f, 0.12f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        Piece(barStool, "BarStoolSeat", PrimitiveType.Cylinder, new Vector3(0f, 0.72f, 0f), new Vector3(0.45f, 0.05f, 0.45f), new Quaternion(0f, 0f, 0f, 1f), kit.fabricBurgundy);
        Piece(barStool, "BarStoolFoot", PrimitiveType.Cylinder, new Vector3(0f, 0.04f, 0f), new Vector3(0.42f, 0.04f, 0.42f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        kit.barStool = Save(barStool);

        var cashierCounter = new GameObject("Kit_CashierCounter");
        Piece(cashierCounter, "CashierCounter", PrimitiveType.Cube, new Vector3(0f, 0.53f, 0f), new Vector3(3.2f, 1.06f, 1f), new Quaternion(0f, 0f, 0f, 1f), kit.woodDark);
        Piece(cashierCounter, "CashierTop", PrimitiveType.Cube, new Vector3(0f, 1.1f, 0f), new Vector3(3.45f, 0.12f, 1.15f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        Piece(cashierCounter, "CashierBrassBars", PrimitiveType.Cube, new Vector3(-1.6f, 1.95f, 0f), new Vector3(0.035f, 1.55f, 0.035f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        Piece(cashierCounter, "CashierBrassBars", PrimitiveType.Cube, new Vector3(-0.8f, 1.95f, 0f), new Vector3(0.035f, 1.55f, 0.035f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        Piece(cashierCounter, "CashierBrassBars", PrimitiveType.Cube, new Vector3(0f, 1.95f, 0f), new Vector3(0.035f, 1.55f, 0.035f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        Piece(cashierCounter, "CashierBrassBars", PrimitiveType.Cube, new Vector3(0.8f, 1.95f, 0f), new Vector3(0.035f, 1.55f, 0.035f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        Piece(cashierCounter, "CashierBrassBars", PrimitiveType.Cube, new Vector3(1.6f, 1.95f, 0f), new Vector3(0.035f, 1.55f, 0.035f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        Piece(cashierCounter, "CashierHeader", PrimitiveType.Cube, new Vector3(0f, 2.75f, 0f), new Vector3(3.4f, 0.2f, 0.15f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        kit.cashierCounter = Save(cashierCounter);

        var chandelier = new GameObject("Kit_Chandelier");
        Piece(chandelier, "ChandelierStem", PrimitiveType.Cylinder, new Vector3(0f, 0.32f, 0f), new Vector3(0.065f, 0.3f, 0.065f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        Piece(chandelier, "ChandelierHub", PrimitiveType.Cylinder, new Vector3(0f, 0f, 0f), new Vector3(0.32f, 0.12f, 0.32f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        Piece(chandelier, "ChandelierArm", PrimitiveType.Cube, new Vector3(0f, 0f, 0.4f), new Vector3(0.045f, 0.045f, 0.85f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        Piece(chandelier, "ChandelierLamp", PrimitiveType.Sphere, new Vector3(0f, 0f, 0.8f), new Vector3(0.2f, 0.3f, 0.2f), new Quaternion(0f, 0f, 0f, 1f), kit.plasterCream);
        Piece(chandelier, "ChandelierArm", PrimitiveType.Cube, new Vector3(0.34641016f, 0f, 0.2f), new Vector3(0.045f, 0.045f, 0.85f), new Quaternion(0f, 0.5f, 0f, 0.8660254f), kit.brassGold);
        Piece(chandelier, "ChandelierLamp", PrimitiveType.Sphere, new Vector3(0.69282032f, 0f, 0.4f), new Vector3(0.2f, 0.3f, 0.2f), new Quaternion(0f, 0f, 0f, 1f), kit.plasterCream);
        Piece(chandelier, "ChandelierArm", PrimitiveType.Cube, new Vector3(0.34641016f, 0f, -0.2f), new Vector3(0.045f, 0.045f, 0.85f), new Quaternion(0f, 0.8660254f, 0f, 0.5f), kit.brassGold);
        Piece(chandelier, "ChandelierLamp", PrimitiveType.Sphere, new Vector3(0.69282032f, 0f, -0.4f), new Vector3(0.2f, 0.3f, 0.2f), new Quaternion(0f, 0f, 0f, 1f), kit.plasterCream);
        Piece(chandelier, "ChandelierArm", PrimitiveType.Cube, new Vector3(4.8985872e-17f, 0f, -0.4f), new Vector3(0.045f, 0.045f, 0.85f), new Quaternion(0f, 1f, 0f, 6.123234e-17f), kit.brassGold);
        Piece(chandelier, "ChandelierLamp", PrimitiveType.Sphere, new Vector3(9.7971744e-17f, 0f, -0.8f), new Vector3(0.2f, 0.3f, 0.2f), new Quaternion(0f, 0f, 0f, 1f), kit.plasterCream);
        Piece(chandelier, "ChandelierArm", PrimitiveType.Cube, new Vector3(-0.34641016f, 0f, -0.2f), new Vector3(0.045f, 0.045f, 0.85f), new Quaternion(0f, 0.8660254f, 0f, -0.5f), kit.brassGold);
        Piece(chandelier, "ChandelierLamp", PrimitiveType.Sphere, new Vector3(-0.69282032f, 0f, -0.4f), new Vector3(0.2f, 0.3f, 0.2f), new Quaternion(0f, 0f, 0f, 1f), kit.plasterCream);
        Piece(chandelier, "ChandelierArm", PrimitiveType.Cube, new Vector3(-0.34641016f, 0f, 0.2f), new Vector3(0.045f, 0.045f, 0.85f), new Quaternion(0f, 0.5f, 0f, -0.8660254f), kit.brassGold);
        Piece(chandelier, "ChandelierLamp", PrimitiveType.Sphere, new Vector3(-0.69282032f, 0f, 0.4f), new Vector3(0.2f, 0.3f, 0.2f), new Quaternion(0f, 0f, 0f, 1f), kit.plasterCream);
        kit.chandelier = Save(chandelier);

        var casinoWallPanel = new GameObject("Kit_CasinoWallPanel");
        Piece(casinoWallPanel, "SideWall", PrimitiveType.Cube, new Vector3(0f, 1.5f, 0f), new Vector3(2f, 3f, 0.15f), new Quaternion(0f, 0f, 0f, 1f), kit.plasterCream);
        Piece(casinoWallPanel, "Wainscot", PrimitiveType.Cube, new Vector3(0f, 0.65f, -0.1f), new Vector3(2f, 1.3f, 0.08f), new Quaternion(0f, 0f, 0f, 1f), kit.woodDark);
        Piece(casinoWallPanel, "GoldChairRail", PrimitiveType.Cube, new Vector3(0f, 1.32f, -0.16f), new Vector3(2f, 0.06f, 0.04f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        Piece(casinoWallPanel, "CrownMolding", PrimitiveType.Cube, new Vector3(0f, 2.85f, -0.16f), new Vector3(2f, 0.15f, 0.08f), new Quaternion(0f, 0f, 0f, 1f), kit.brassGold);
        kit.casinoWallPanel = Save(casinoWallPanel);

    }

    static void Place(GameObject prefab, GameObject parent, Vector3 position, Quaternion rotation)
    {
        var go = (GameObject)PrefabUtility.InstantiatePrefab(prefab, parent.transform);
        go.transform.localPosition = position;
        go.transform.localRotation = rotation;
    }

    static void Piece(GameObject parent, string name, PrimitiveType type, Vector3 position, Vector3 scale, Quaternion rotation, Material material)
    {
        var go = GameObject.CreatePrimitive(type);
        go.name = name;
        go.transform.SetParent(parent.transform, false);
        go.transform.localPosition = position;
        go.transform.localScale = scale;
        go.transform.localRotation = rotation;
        go.GetComponent<Renderer>().sharedMaterial = material;
        go.GetComponent<Renderer>().shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
        Object.DestroyImmediate(go.GetComponent<Collider>());
        if (type == PrimitiveType.Cube) go.AddComponent<BoxCollider>();
        else if (type == PrimitiveType.Sphere) go.AddComponent<SphereCollider>();
        else go.AddComponent<MeshCollider>().convex = true;
    }

    static GameObject Save(GameObject root)
    {
        foreach (var transform in root.GetComponentsInChildren<Transform>()) transform.gameObject.isStatic = true;
        var prefab = PrefabUtility.SaveAsPrefabAsset(root, "Assets/Content/StyleKit/Prefabs/" + root.name + ".prefab");
        Object.DestroyImmediate(root);
        return prefab;
    }
}
